spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/campsite?useUnicode=true
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        user_sql_comments: true
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create

maxAvailabilityDay: 30